# Options reference
# https://github.com/neighborhood999/fiveN1-rent-scraper#urljumpip-code-list
CONDITIONS: {
    'is_new_list': '1',
    'type': '1', # 類型???
    'kind': '1', # 類型
    'region': '1', # 位置：台北市
    'section': '4,3,5,7,1', # 區域：中山大安信義中正松山
    'searchtype': '1', # 依鄉鎮選擇
    'regionid': '1', # 區域：台北市
    'rentprice': '0,36000', # 租金
    'patternMore': '3,4', # 格局
    'option': 'cold', # 提供設備
    'other': 'cook', # 其他條件
    'hasimg': '1', # 有房屋圖片
    'not_cover': '1', # 排除頂樓加蓋
    'order': 'refreshtime', # 默認更新時間排序
    'orderType': 'undefined'
}

DETAIL_URL: "https://rent.591.com.tw/rent-detail-{house_id}.html"
